# Generated by Django 3.0 on 2019-12-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('national_id', models.CharField(max_length=10, unique=True)),
                ('personal_id', models.CharField(max_length=10, unique=True)),
                ('tel', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=200)),
                ('is_married', models.BooleanField()),
                ('salary', models.PositiveIntegerField()),
            ],
        ),
    ]
