# Generated by Django 3.0 on 2019-12-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='id',
        ),
        migrations.AlterField(
            model_name='employees',
            name='personal_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
