# Generated by Django 3.0 on 2019-12-21 10:43

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191221_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='tel',
        ),
        migrations.AddField(
            model_name='employees',
            name='tele',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
