# Generated by Django 3.0 on 2019-12-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191221_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='is_married',
            field=models.BooleanField(default=False),
        ),
    ]
