# Generated by Django 3.0 on 2019-12-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191221_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='age',
            field=models.SmallIntegerField(default=0),
        ),
    ]
