# Generated by Django 3.0 on 2019-12-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_employees_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('none', 'None')], default='none', max_length=6),
        ),
    ]
