# Generated by Django 3.0 on 2019-12-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_employees_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('none', 'None')], default='none', max_length=6),
        ),
    ]
