# Generated by Django 3.0 on 2019-12-24 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191224_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
